#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestAndroid.Resource", IsApplication=true)]

namespace TestAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int btnClear = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int btnClearFromServer = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int btnConnect = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int btnSendToServer = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int editTextIP = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int editTextPort = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int editTextSendServer = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int rB_CR = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int rB_CR_LF = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int rB_LF = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int rB_NoEOL = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int radioGroup = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int textView3 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int textViewInfo = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int clear = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int connect = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int ip = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int logToFile = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int logToWindow = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int port = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int rb_CR = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int rb_CR_LF = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int rb_LF = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int rb_NoEOL = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int recivedFromServerLabel = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int sVer = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int send = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int sendDataLabel = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int serverInfoLabel = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f030000
			public const int device_filter = 2130903040;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
